# Generated by Django 6.0.2 on 2026-02-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('team_type', models.CharField(choices=[('solo', 'solo'), ('duo', 'duo')], max_length=10)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=10)),
                ('student_no', models.CharField(max_length=10, unique=True)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('year', models.CharField(choices=[('1', '1st'), ('2', '2nd')], max_length=1)),
                ('gender', models.CharField(max_length=10)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('IT', 'IT'), ('EEE', 'EEE'), ('ME', 'ME'), ('CE', 'CE'), ('CSIT', 'CSIT'), ('AIML', 'AIML'), ('OTHERS', 'OTHERS')], max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='registration.team')),
            ],
        ),
    ]
