# Generated by Django 6.0.2 on 2026-02-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_player_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
