# Generated by Django 6.0.2 on 2026-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_player_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='roll_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='student_no',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
