# Generated by Django 6.0.2 on 2026-03-11 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='registration.team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
